theme:
  name: "material"
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
site_name: Upf topicos especiais II - Aulas

nav:
  - Home: index.md
  - Aula 1 — Node.js e APIs HTTP: aula1/aula1.md
  - Aula 2 — Contas a receber e rotas HTTP: aula2/aula2.md
  - Aula 3 — Validações com Zod e organização do backend: aula3/aula3.md
  - Aula 4 — MongoDB e persistência de dados:
      - Tutorial principal: aula4/aula4.md
      - Tutorial da dinâmica CRUD: aula4/tutorial-crud-persistido.md
